/*-----------待办任务查询视图-------------*/
/*查询方法*/
SELECT * FROM V_TASKLIST WHERE ASSIGNEE = ：userId OR CANDIDATE = ：userId;
CREATE VIEW V_TASKLIST AS
SELECT 
	A.ID_ AS TASK_ID,
  A.PROC_INST_ID_ PROC_INST_ID,
  A.TASK_DEF_KEY_ AS ACT_ID,
  A.NAME_ AS ACT_NAME,
  A.ASSIGNEE_ AS ASSIGNEE,
  A.DELEGATION_ AS DELEGATION_ID,
  A.DESCRIPTION_ AS DESCRIPTION,
  DATE_FORMAT(A.CREATE_TIME_, '%Y-%m-%d %T') AS CREATE_TIME,
  DATE_FORMAT(A.DUE_DATE_,'%Y-%m-%d %T') AS DUE_DATE,
  I.USER_ID CANDIDATE
FROM ACT_RU_TASK A
LEFT JOIN (
	SELECT DISTINCT * FROM (
			SELECT TASK_ID_, USER_ID_ AS USER_ID
			 FROM ACT_RU_IDENTITYLINK I, ACT_RU_TASK T
				WHERE TASK_ID_ IS NOT NULL
					AND USER_ID_ IS NOT NULL
					AND I.TASK_ID_ = T.ID_
					AND T.ASSIGNEE_ IS NULL
					AND TYPE_ = 'candidate'
			 UNION
			 SELECT TASK_ID_, R.USER_ID
				 FROM ACT_RU_IDENTITYLINK I,SYS_USER_ROLE R,ACT_RU_TASK T
				WHERE I.TASK_ID_ IS NOT NULL
					AND I.GROUP_ID_ IS NOT NULL
					AND I.TASK_ID_ = T.ID_
					AND T.ASSIGNEE_ IS NULL
					AND TYPE_ = 'candidate'
					AND I.GROUP_ID_ = R.ROLE_ID
	)U
) I/*--候选组和业务上的角色用户表关联*/
ON A.ID_ = I.TASK_ID_ 